### ISSUE TITLE
모달 이슈

### ISSUE THREAD

**Issue by BrightJun96** [BrightJun96/resume#1]
## 모달 내용이 스크롤 안되는 이슈

모달 내용이 일정 이상 되면 스크롤 되지않고 짤리는 이슈를 발견하였다.  
이에 대하여 모달섹션 컨테이너인 .modal에 스크롤을 할 수 있게 overflow:scroll를 설정해주었다.

```css
.modal {
  overflow: scroll;
}
```

## modal from visibility : hidden to display : none

.modal에 visibility : hidden에서 display: none으로 지정하였고 버튼을 클릭하여 .open-modal클래스가 추가됬을 때 display: flex justify-content: center, align-items: center가 되도록 구현하였다.

visibility:hidden는 엘리먼트가 공간은 차지하지만 보이지 않게 하는 것이고  
display:none은 요소가 공간 자체를 차지하지않는다.

따라서 .open-modal클래스가 없는 상태에서는 모달 섹션 요소가 없게 하고 클래스가 있는 상태에서는 섹션 요소가 나타나게 해준다.

위와 같이 변경한 이유는 해당요소가 존재하지않을 때는 요소자체가 없어져야되는 것이 맞다고 생각하여 변경하였다.

**Before**

```css
.modal {
  visibility: hidden;
  display: flex;
  justify-content: center;
  align-items: center;
}

.open-modal {
  visibility: visible;
}
```

**After**

```css
.modal {
  display: none;
}

.open-modal {
  display: flex;
  justify-content: center;
  align-items: center;
}
```
